[window]
opacity = 0.7
blur = true
decorations = "Full"
padding.x = 5
padding.y = 5
dynamic_title = true

[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"
]

[font]
size=13
